

services:
  noxer_db:
    container_name: noxer_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noxer_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  api_server:
    depends_on:
      - noxer_db
    container_name: noxer_api_server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
