

services:
  db:
    container_name: noxer_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noxer_db
    ports:
      - "5432:5432"